### ISSUE TITLE
Error in Install-Scripts/Project?

### ISSUE THREAD

**Issue by ManuelNGoga** [andrew-s-taylor/public#10]
Hi Andrew,
I had tested both your solutions for Visio and Project installation via Company Portal via Win32 app [Deploy-Application.intunewin].

The installation of Visio runs without any problems. Very nice 👍 For Project I get an error message ("Error unzipping downloaded content. (0x87D30067)").
Had only tested it on two devices so far, but same message on both. I didn't notice anything that could cause the error and also couldn't find any differences in the scripts.

**Comment by andrew-s-taylor** [comment]
Sometimes that's a bug when packaging, I've just re-packaged and uploaded it again, can you try that one please?

**Comment by ManuelNGoga** [comment]
Hey, the new package has worked. Thanks for your help, saved me a lot of time! 🥇
