### ISSUE TITLE
Iteration typo/bug

### ISSUE THREAD

**Issue by andreasrl** [andrew-s-taylor/public#11]
https://github.com/andrew-s-taylor/public/blob/065e0f16d1641069466af563902f242426b6f587/Powershell%20Scripts/Intune/SyncAllIntuneDevices.ps1#L134

Pretty sure there's a bug here (line 134 and above). To be fair I haven't run it yet, but it looks to me like it needs a little cleanup to work as expected... right?

**Comment by andrew-s-taylor** [comment]
Thank you, I'd missed that, should be sorted now
