### ISSUE TITLE
bloatware.ps1 The specified path format is not supported

### ISSUE THREAD

**Issue by maracre** [andrew-s-taylor/public#13]
With the RemoveBloat.ps1, we get the error The specified path format is not supported when im executing it on our machines.
We only use the German Language Pack.

**Comment by andrew-s-taylor** [comment]
Can you add the logs in here please so I can see which part is failing?

**Comment by maracre** [comment]
Here is the requested log. Thanks

Von: Andrew Taylor ***@***.***>
Gesendet: Freitag, 10. März 2023 13:48
An: andrew-s-taylor/public ***@***.***>
Cc: Marcel Berger ***@***.***>; Author ***@***.***>
Betreff: [EXTERN] - Re: [andrew-s-taylor/public] bloatware.ps1 The specified path format is not supported (Issue #13)

Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Can you add the logs in here please so I can see which part is failing?

-

**Comment by andrew-s-taylor** [comment]
I've just tested on a machine with the German Language pack installed and it seems to be working ok.
Is it running with elevated permissions?

**Comment by maracre** [comment]
Yes we run it with elevated permission, with a local Admin. I also tried it with the inbuild detection where its open up with elevated permission, where the inbuild UAC ask for Admin Privilages.

**Comment by andrew-s-taylor** [comment]
This should be sorted in the latest  multi-language update
