### ISSUE TITLE
Just to information - download links not works, as the links here is time based

### ISSUE THREAD

**Issue by michaelmsonne** [andrew-s-taylor/public#15]
Just to information here, that the download links not works as the links here is time based (for https://software.download.prss.microsoft.com) and have an expire time (is expired btw.) so cant be hardcoded 😉

Script: create-windows-iso-with-apjson.ps1

Code: https://github.com/andrew-s-taylor/public/blob/c8c533931a240421f0ba420f417efe2bea71c098/Powershell%20Scripts/Intune/create-windows-iso-with-apjson.ps1#L55C1-L56C232

I will think of that is possible 🙃

**Comment by andrew-s-taylor** [comment]
Ah, that's annoying.  I'll try and find another way

**Comment by michaelmsonne** [comment]
Yes - I will try also if there is a smart way to 👍

**Comment by andrew-s-taylor** [comment]
I've updated it to 1.0.3 which uses Fido to grab the URL.  It's also amended now to automatically find the latest Windows versions.

**Comment by michaelmsonne** [comment]
Yes - i found that tool here yesterday to, but got not time to look into it for the script yet.
But cool 👍
