### ISSUE TITLE
De-Bloat: Autopilot deployment failure due to errors from SetACL

### ISSUE THREAD

**Issue by mato** [andrew-s-taylor/public#17]
Hi,

first of all, I'd like to say that you, Sir, are a genius and thank you for developing the De-Bloat script. I'll buy you some beers if we ever meet up.

On to the actual problem. I have here a new ASUS laptop which I cannot get through Autopilot deployment no matter what I try, with various failures during ESP. After looking at the AgentExecutor logs, I _think_ De-Bloat may be part of the problem. I'm deploying the script in the "device context" (i.e. run as logged on user is not set), running in a 64-bit PowerShell host: 

```
<![LOG[Adding argument powershell with value C:\Program Files (x86)\Microsoft Intune Management Extension\Policies\Scripts\00000000-0000-0000-0000-000000000000_2388056c-1ccc-45f4-b9c0-5fa96d3a6fd8.ps1 to the named argument list.]LOG]!><time="13:18:50.9932705" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[Powershell option gets invoked]LOG]!><time="13:18:50.9932705" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[C:\Program Files (x86)\Microsoft Intune Management Extension\Policies\Scripts\00000000-0000-0000-0000-000000000000_2388056c-1ccc-45f4-b9c0-5fa96d3a6fd8.ps1]LOG]!><time="13:18:50.9932705" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[C:\Program Files (x86)\Microsoft Intune Management Extension\Policies\Results\00000000-0000-0000-0000-000000000000_2388056c-1ccc-45f4-b9c0-5fa96d3a6fd8.output]LOG]!><time="13:18:50.9932705" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[C:\Program Files (x86)\Microsoft Intune Management Extension\Policies\Results\00000000-0000-0000-0000-000000000000_2388056c-1ccc-45f4-b9c0-5fa96d3a6fd8.error]LOG]!><time="13:18:50.9970805" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[C:\Program Files (x86)\Microsoft Intune Management Extension\Policies\Results\00000000-0000-0000-0000-000000000000_2388056c-1ccc-45f4-b9c0-5fa96d3a6fd8.timeout]LOG]!><time="13:18:50.9970805" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[Prepare to run Powershell Script ..]LOG]!><time="13:18:50.9970805" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[scriptParams is ]LOG]!><time="13:18:50.9970805" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[cmd line for running powershell is -NoProfile -executionPolicy bypass -file  "C:\Program Files (x86)\Microsoft Intune Management Extension\Policies\Scripts\00000000-0000-0000-0000-000000000000_2388056c-1ccc-45f4-b9c0-5fa96d3a6fd8.ps1" ]LOG]!><time="13:18:50.9970805" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[runAs32BitOn64 = False, so Disable Wow64FsRedirection]LOG]!><time="13:18:50.9970805" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[PowerShell path is C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe]LOG]!><time="13:18:50.9970805" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[[Executor] created powershell with process id 8852]LOG]!><time="13:18:51.0155363" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[Powershell exit code is 0]LOG]!><time="13:19:46.5702148" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[lenth of out=17650]LOG]!><time="13:19:46.5702148" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[lenth of error=156]LOG]!><time="13:19:46.5702148" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[error from script =
SetACL finished with error(s): 
SetACL error message: The call to SetNamedSecurityInfo () failed
Operating system error message: Access is denied.


]LOG]!><time="13:19:46.5702148" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOGrshell script is successfully executed.]LOG]!><time="13:19:46.5702148" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[write output done. output = The folder 'C:\ProgramData\Debloat' doesn't exist. This folder will be used for storing logs created after the script runs. Creating now.

<snip DeBloat output>

Uninstalling ASUS Business Manager
Uninstalling ASUS Business Manager
Completed
Transcript stopped, output file is C:\ProgramData\Debloat\Debloat.log



, error = 
SetACL finished with error(s): 
SetACL error message: The call to SetNamedSecurityInfo () failed
Operating system error message: Access is denied.


]LOG]!><time="13:19:46.5759426" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[Revert Wow64FsRedirection]LOG]!><time="13:19:46.5759426" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
<![LOG[Agent executor completed.]LOG]!><time="13:19:46.5759426" date="10-3-2023" component="AgentExecutor" context="" type="1" thread="1" file="">
```

I've snipped the actual DeBloat output above, as I can see no errors there. 

What I _think_ is happening is this:

1. Intune treats any error output from the script as "it failed".
2. It runs the script once, thinks it failed.
3. It then goes on to deploy various apps to the machine.
4. At some point (still displaying the ESP), it runs the script again, and it again thinks it failed.
5. Repeat steps 3, 4 one more time.
6. Somewhere in between steps 3 and 5 Intune gets very confused, presumably because DeBloat has removed some apps Intune thought it installed.
7. Boom! (ESP shows some or other obscure error,  and/or application deployment timeout.)

I'm not sure how to handle this, as I don't see what specific SetACL.exe call in the script is failing from the logs (since the errors go to a separate stream/log). What I'm going to try next is changing all of the SetACL.exe invocations in the script to add -ignoreerr in the hope that will at least silence the error, and stop Intune from trying to re-run the script.

Any other ideas?

**Comment by andrew-s-taylor** [comment]
Hi,
Can you confirm what these three are set to:
Run this script using the logged on credentials

Enforce script signature check

Run script in 64 bit PowerShell Host

Does Autopilot progress to the installing apps phase?  If deployed in the device context, this should run in the detecting apps section and then when it moves on to installing, it usually means scripts have completed (whether successfully or not)

**Comment by mato** [comment]
> Run this script using the logged on credentials

Set to no.

> Enforce script signature check

Set to no.

> Run script in 64 bit PowerShell Host

Set to yes.

> Does Autopilot progress to the installing apps phase? If deployed in the device context, this should run in the detecting apps section and then when it moves on to installing, it usually means scripts have completed (whether successfully or not)

How can I tell? The ESP seems to suggest that it does; however the Diagnostics page (Ctrl-Shift-D) shows "Device-Targeted Apps Installation" as "The operation is still in progress" and "User-Targeted Apps Installation" and following steps with an exclamation mark and "time not available, required warning data incomplete or missing".

**Comment by andrew-s-taylor** [comment]
Hi,
Can you share the log created by the debloat script?
C:\ProgramData\Debloat\Debloat.log
That should narrow down exactly which command is failing and why
