### ISSUE TITLE
detection logic

### ISSUE THREAD

**Issue by mantis** [andrew-s-taylor/public#18]
Hi Andrew,

https://github.com/andrew-s-taylor/public/blob/30affef74fa7494338fe762d52c106f9856cead3/Powershell%20Scripts/Intune/deploy-winget-win32-multiple.ps1#L2492

When detecting the .net 6 desktop runtime, I'm finding this code block is working on windows 11 , not windows 10 (As I write this, i'm just realising that I don't think i've deployed winget to windows 10 devices via intune...)

However - looking at the code:

a) the start-sleep 10 would seem redundant - if the first bit is just resolving the path, there doesn't seem to be an obvious reason to add a 10 second delay

b) Running this script as an admin seems to fail as the path isn't accessible (presumably as it's deploying from that location to C:\Users\paul\AppData\Local\Microsoft\WindowsApps\winget.exe)

**Comment by mantis** [comment]
re 2 - I think I managed to not run as admin, so actually ignore that and i'll come back to you.

**Comment by andrew-s-taylor** [comment]
Detection logic fixed in latest version
