### ISSUE TITLE
Invoke-Executable issue?

### ISSUE THREAD

**Issue by MA-Jason-Coombes** [andrew-s-taylor/public#19]
Hi Andrew,

Please can you assit,

We've had some issues in our own pipeline regarding the new Content prep tool breaking the invoke command (https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/issues/111), I was wondering if this was the case with your script too as I'm doing some testing with it currently. 

error in powershell terminal before the graph authentication hits:
; `+ Invoke-WebRequest -Uri $intuneapputilurl -OutFile $intuneapputiloutpu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], 
WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Invoke-WebRequest : The request was aborted: The connection was closed unexpectedly.
At C:\Users\Name\OneDrive - Company\Desktop\deploy-winget-win32-multiple.ps1:390 char:1
+ Invoke-WebRequest -Uri $intuneapputilurl -OutFile $intuneapputiloutpu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

Remediation gets created, groups get created but the ContentPrep tool doesn't create the .intunewin, I get this error after selecting "go" from the grid of applications (I selected Notepad++)

`. : The term 'c:\temp\934-2312041512\IntuneWinAppUtil.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At C:\Users\Name\OneDrive - Company\Desktop\deploy-winget-win32-multiple.ps1:2444 char:7
+     . $intuneapputiloutput -c "$apppath" -s "$setupfilename" -o "$app ...
+       ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\temp\934-231...eWinAppUtil.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

(Microsoft Windows NT 10.0.22631.0)
Host Application: C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe
Process ID: 20100
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

Regards,
Jason

**Comment by andrew-s-taylor** [comment]
Looks like something is blocking you from downloading the intunewinapputil.exe.  Unable to replicate issue

**Comment by lammy666** [comment]
While not directly related to this,  I have downloaded all the external downloads, modified the code to use a local copy of the file and wrapped it all up in the Intunewin file.  This way there is no reliance on external downloads.

**Comment by andrew-s-taylor** [comment]
That's a good approach in restricted environments.  I have the download in to ensure it's always getting the latest versions
