### ISSUE TITLE
Can't get the apps to deploy, getting stuck at uploading.

### ISSUE THREAD

**Issue by cs4m** [andrew-s-taylor/public#20]
Hi and thanks for an amazing script (deploy-winget-win32-multiple), it truly is.

But,
whenever I run the script, everything works flawlessly up until step 2690 were it throws an error.
If I look in Intune the app is there with all info but stuck in a state were it says:
 "Your app is not ready yet. If app content is uploading, wait for it to finish. If app content is not uploading, try creating the app again."
The error from log just before the end is:
POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/8d486cd1-dcdc-4c85-8bb7-483c540ce89a/assign
HTTP/1.1 400 Bad Request
Message\": \"Invalid operation: app's PublishingState is not 'Published'"
I can't figure out what I'm missing or doing wrong?
If I pick the intunewin-file created and upload it all works fine.

**Comment by andrew-s-taylor** [comment]
Hi, do you have a firewall or anything which could be blocking the file upload?

**Comment by cs4m** [comment]
No I cannot see that it should have any issues with access since I'm only using standard Defender and no special setup. I even turned off firewall just to make sure. Tried on both my tenants with same result.
If you have any troubleshooting advice please let me know

**Comment by VSBernhard** [comment]
Hello, I also had this issue. I changed to app-based authentication and everything works now great.

**Comment by cs4m** [comment]
Tried both and still the same. Added both secret and a certificate but it throws - Invalid operation: app's PublishingState is not   
     | 'Published', and groups and app is there, not just uploaded. Frustrating :)

**Comment by andrew-s-taylor** [comment]
Do you get a percentage bar when the app is attempting to upload?

**Comment by gorilla1968** [comment]
Hello
I'm using a German operating system. The bug seems to be in Winget's search function. I've written my own function. This will make your script work flawlessly.

**Comment by andrew-s-taylor** [comment]
If you use PowerShell7 it uses the new Winget PS module which works ok with multiple languages.
Happy to add your function with some language logic around it though if you are interested in sharing it

**Comment by cs4m** [comment]
Yes, I get a "bar" saying Uploading File to Azure Storage 1 of 1.
The log is below with random app;

> Installing Intune modules if required (current user scope)
Installing Intune modules if required (current user scope)
PowerShell YAML Already Installed
Installing Microsoft Graph modules if required (current user scope)
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Script has been updated, please download the latest version from https://raw.githubusercontent.com/andrew-s-taylor/public/main/Powershell%20Scripts/Intune/deploy-winget-win32-multiple.ps1
Directory already existed

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2023-12-27    22:10                255-2312271009
winget already installed
Running PowerShell 7, importing module
Microsoft Winget Client Already Installed
Version 2 module detected
Connected to Intune tenant

    Directory: C:\temp\255-2312271009

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2023-12-27    22:11                4gray.iptvnator
Directory c:\temp\255-2312271009\\4gray.iptvnator Created
Created f22d8a25-65af-416d-adab-20c8418c54dd for installing iptvnator
Created 0a14945d-b513-49e9-bb81-664249937dd1 for uninstalling iptvnator
Script created at c:\temp\255-2312271009\\4gray.iptvnator\install4gray.iptvnator.ps1
Script created at c:\temp\255-2312271009\\4gray.iptvnator\uninstall4gray.iptvnator.ps1
Script created at c:\temp\255-2312271009\\4gray.iptvnator\detection4gray.iptvnator.ps1
Success
Proactive Remediation Created and Assigned for iptvnator
INFO   Validating parameters
INFO   Validated parameters within 3 milliseconds
INFO   Compressing the source folder 'c:\temp\255-2312271009\\4gray.iptvnator' to 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPac
kage\Contents\IntunePackage.intunewin'
INFO   Calculated size for folder 'c:\temp\255-2312271009\\4gray.iptvnator' is 1290 within 0 milliseconds
INFO   Compressed folder 'c:\temp\255-2312271009\\4gray.iptvnator' successfully within 17 milliseconds
INFO   Checking file type
INFO   Checked file type within 1 milliseconds
INFO   Encrypting file 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\IntunePackage.intunewin'
INFO   'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\IntunePackage.intunewin' has been encrypted successfully with
in 6 milliseconds
INFO   Computing SHA256 hash for C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\286c0882-a469-4515-8e33-dc8d9c56adf1
INFO   Computed SHA256 hash for 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\286c0882-a469-4515-8e33-dc8d9c56adf1
' within 6 milliseconds
INFO   Computing SHA256 hash for C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\IntunePackage.intunewin
INFO   Computed SHA256 hash for C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\IntunePackage.intunewin within 3 mill
iseconds
INFO   Copying encrypted file from 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\286c0882-a469-4515-8e33-dc8d9c56a
df1' to 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\IntunePackage.intunewin'
INFO   File 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Contents\IntunePackage.intunewin' got updated successfully within
 2 milliseconds
INFO   Generating detection XML file 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage\Metadata\Detection.xml'
INFO   Generated detection XML file within 17 milliseconds
INFO   Compressing folder 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage' to 'c:\temp\255-2312271009\\4gray.iptvnator\instal
l4gray.iptvnator.intunewin'
INFO   Calculated size for folder 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage' is 2090 within 0 milliseconds
INFO   Compressed folder 'C:\Users\<USERNAME>\AppData\Local\Temp\64b5281d-4bef-4d65-80ef-fa0ab7204106\IntuneWinPackage' successfully within 13 milliseconds
INFO   Removing temporary files
INFO   Removed temporary files within 1 milliseconds
INFO   File 'c:\temp\255-2312271009\\4gray.iptvnator\install4gray.iptvnator.intunewin' has been generated successfully


[=================================================]   100%
INFO   Done!!!
Intunewin c:\temp\255-2312271009\\4gray.iptvnator\install4gray.iptvnator.intunewin Created
PS>TerminatingError(Write-Error): "Cannot bind argument to parameter 'Exception' because it is null."
>> TerminatingError(Write-Error): "Cannot bind argument to parameter 'Exception' because it is null."
Write-Error: <SCRIPTPATH>deploy-winget-win32-multiple.ps1:2716:18
Line |
2716 |  … appupload = Invoke-UploadWin32Lob -SourceFile "$appfile" -DisplayName …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Aborting with exception: System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Exception' because it is null.    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Invoke-UploadWin32Lob: <SCRIPTPATH>deploy-winget-win32-multiple.ps1:2716:18
Line |
2716 |  … appupload = Invoke-UploadWin32Lob -SourceFile "$appfile" -DisplayName …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Aborting with exception: System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Exception' because it is null.  
     | at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)    at
     | System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)    at
     | System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)    at
     | System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

0

BaseResponse      : StatusCode: 201, ReasonPhrase: 'Created', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
                    {
                      Server: Windows-Azure-Blob/1.0
                      Server: Microsoft-HTTPAPI/2.0
                      x-ms-request-id: 350d61e6-001e-001c-2b09-390043000000
                      x-ms-version: 2017-04-17
                      x-ms-request-server-encrypted: true
                      Date: Wed, 27 Dec 2023 21:11:54 GMT
                      Content-Length: 0
                      Content-MD5: zB/MJY22l1HbHxRJJZAfkw==
                    }
Content           : {}
Headers           : {[Server, System.String[]], [x-ms-request-id, System.String[]], [x-ms-version, System.String[]], [x-ms-request-server-encrypted, System.String[]]
                    …}
RawContent        : HTTP/1.1 201 Created
                    Server: Windows-Azure-Blob/1.0
                    Server: Microsoft-HTTPAPI/2.0
                    x-ms-request-id: 350d61e6-001e-001c-2b09-390043000000
                    x-ms-version: 2017-04-17
                    x-ms-request-server-encrypted: true
                    Date: Wed, 27 Dec 2023 21:11:54 GMT
                    Content-Length: 0
                    Content-MD5: zB/MJY22l1HbHxRJJZAfkw==


RawContentLength  : 0
RawContentStream  : Microsoft.PowerShell.Commands.WebResponseContentMemoryStream
RelationLink      : {}
StatusCode        : 201
StatusDescription : Created


iptvnator Created and uploaded
No Available Intent
PS>TerminatingError(Invoke-MgGraphRequest): "POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/11e55060-e4b9-44b8-994b-a365a142f6e2/assign
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: c74c2350-b5cb-45d7-9e57-b9fb9df7d920
client-request-id: b1357248-4d05-4d6e-b140-0c63ffd7e86f
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Sweden Central","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"GV2PEPF00000B2C"}}
Date: Wed, 27 Dec 2023 21:11:56 GMT
Content-Type: application/json
Content-Encoding: gzip

{"error":{"code":"BadRequest","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"Invalid operation: app's PublishingState is not 'Published'. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: b1357248-4d05-4d6e-b140-0c63ffd7e86f - Url: https://fef.msub06.manage.microsoft.com/AppLifecycle_2312/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('11e55060-e4b9-44b8-994b-a365a142f6e2')/microsoft.management.services.api.assign?api-version=5023-09-11\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2023-12-27T21:11:57","request-id":"c74c2350-b5cb-45d7-9e57-b9fb9df7d920","client-request-id":"b1357248-4d05-4d6e-b140-0c63ffd7e86f"}}}"
Invoke-MgGraphRequest: <SCRIPTPATH>deploy-winget-win32-multiple.ps1:2690:5
Line |
2690 |      Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/beta/devi …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/11e55060-e4b9-44b8-994b-a365a142f6e2/assign HTTP/1.1 400 Bad Request Transfer-Encoding: chunked Vary: Accept-Encoding Strict-Transport-Security: max-age=31536000 request-id: c74c2350-b5cb-45d7-9e57-b9fb9df7d920 client-request-id: b1357248-4d05-4d6e-b140-0c63ffd7e86f x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Sweden Central","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"GV2PEPF00000B2C"}} Date: Wed, 27 Dec 2023 21:11:56 GMT Content-Type: application/json Content-Encoding: gzip  {"error":{"code":"BadRequest","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"Invalid operation: app's PublishingState is not 'Published'. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: b1357248-4d05-4d6e-b140-0c63ffd7e86f - Url: https://fef.msub06.manage.microsoft.com/AppLifecycle_2312/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('11e55060-e4b9-44b8-994b-a365a142f6e2')/microsoft.management.services.api.assign?api-version=5023-09-11\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2023-12-27T21:11:57","request-id":"c74c2350-b5cb-45d7-9e57-b9fb9df7d920","client-request-id":"b1357248-4d05-4d6e-b140-0c63ffd7e86f"}}}
Invoke-MgGraphRequest: <SCRIPTPATH>deploy-winget-win32-multiple.ps1:2690:5
Line |
2690 |      Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/beta/devi …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/11e55060-e4b9-44b8-994b-a365a142f6e2/assign HTTP/1.1 400 Bad Request Transfer-Encoding:
     | chunked Vary: Accept-Encoding Strict-Transport-Security: max-age=31536000 request-id: c74c2350-b5cb-45d7-9e57-b9fb9df7d920 client-request-id:
     | b1357248-4d05-4d6e-b140-0c63ffd7e86f x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Sweden
     | Central","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"GV2PEPF00000B2C"}} Date: Wed, 27 Dec 2023 21:11:56 GMT Content-Type: application/json
     | Content-Encoding: gzip  {"error":{"code":"BadRequest","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"Invalid operation: app's PublishingState is not
     | 'Published'. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: b1357248-4d05-4d6e-b140-0c63ffd7e86f - Url:
     | https://fef.msub06.manage.microsoft.com/AppLifecycle_2312/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('11e55060-e4b9-44b8-994b-a365a142f6e2')/microsoft.management.services.api.assign?api-version=5023-09-11\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2023-12-27T21:11:57","request-id":"c74c2350-b5cb-45d7-9e57-b9fb9df7d920","client-request-id":"b1357248-4d05-4d6e-b140-0c63ffd7e86f"}}}

Assigned f22d8a25-65af-416d-adab-20c8418c54dd as Required Install to iptvnator
Assigned 0a14945d-b513-49e9-bb81-664249937dd1 as Required Uninstall to iptvnator
iptvnator packaged and deployed

ClientId               : <CLIENTID>
TenantId               : <TENANTID>
Scopes                 : {Device.Read.All, Device.ReadWrite.All, DeviceManagementApps.ReadWrite.All, DeviceManagementConfiguration.ReadWrite.All…}
AuthType               : Delegated
TokenCredentialType    : InteractiveBrowser
CertificateThumbprint  : 
CertificateSubjectName : 
Account                : <ACCOUNT>
AppName                : Microsoft Graph Command Line Tools
ContextScope           : CurrentUser
Certificate            : 
PSHostVersion          : 2023.8.0
ManagedIdentityId      : 
ClientSecret           : 
Environment            : Global

👍 Selected apps have been deployed to Intune
**********************
PowerShell transcript end
End time: 20231227221156

**Comment by gorilla1968** [comment]
Hello, I have the same issues as cs4m, when I use PS7. The script only works for me, when I take my function for Winget search and PS5.

**Comment by andrew-s-taylor** [comment]
It looks like a fault with a function with PowerShell 7, can you try with 5?

**Comment by andrew-s-taylor** [comment]
> Hello, I have the same issues as cs4m, when I use PS7. The script only works for me, when I take my function for Winget search and PS5.

I'll see if I can create a new function to work with German language in a future release

**Comment by andrew-s-taylor** [comment]
v4.0.10 just added which re-launches PS7 sessions into PS5

**Comment by cs4m** [comment]
That's it! Running it directly from PS5 works great, and it has to be as admin for some reason, although I'm admin on my PC.
Running it from vscode or with pwsh does not work even though it starts PS5, I get below error;
"The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services."
But then I have a way of making it work at least, that's great!
Not sure why it fails with pwsh for me.

**Comment by andrew-s-taylor** [comment]
Excellent, that's good news.  I'll do some more testing with VSCode and PS7 to see what's happening
