### ISSUE TITLE
Start Menu Reset doesn't appear to be working

### ISSUE THREAD

**Issue by Arudinne** [andrew-s-taylor/public#21]
Hello,

I have been testing autopilot with my org and I decided to try out the de-bloat script to clear our all of the manufacturer bloatware.

I am using Dell's SupportAssist to wipe and reinstall the OS. The debloat script does seem to successfully remove all of the unwanted Dell applications, however it seems the Start Menu reset is not working for whichever account I use to login to the device the first time. All subsequent users have a clean start menu as expected. I have tried this with multiple test user accounts.

All test user accounts have M365 E5 licenses.

OS: Windows 11 Pro 22H2 (Build 22621.2134)
Device: Latitude 5430

The log indicates it is successfully cleaning it, and that does seem true for everyone but the first user.

I would appreciate any advice.

**Comment by andrew-s-taylor** [comment]
Hi,
Are you running the script during OOBE or after the user has logged in?  The start menu only applies on first login so if the account is already in-use, it won't make any changes to that one

**Comment by Arudinne** [comment]
Based on the way it is acting perhaps it is not running during OOBE, but I am not sure how I would tell.

I have the script assigned to a group the device is in and I am using a User-Drive Hybrid Joined profile.

How would I ensure the script to run during Autopillots OOBE?

**Comment by andrew-s-taylor** [comment]
If it's assigned to a device group, it should run during ESP on Autopilot, on the "detecting apps" phase

**Comment by Arudinne** [comment]
The log file indicates it is running as the account <DOMAIN>/System. All the test accounts I have logged in with are non-admins if that matters.

**Comment by Arudinne** [comment]
I've tried it again with the win32 version. I set this app and our VPN client as the only "blockers" in ESP.

Results are the same.

**Comment by Arudinne** [comment]
An update: It seems to work fine with Entra joining only.

**Comment by andrew-s-taylor** [comment]
Ah, I wonder if the hybrid join is kicking in prior to the script running.  Do you have a start menu policy configured?  That should pick up the logged in user.

**Comment by Arudinne** [comment]
There is no GPO or Intune start menu policy configured.

**Comment by andrew-s-taylor** [comment]
I would normally suggest adding one of those alongisde the script so you can add items your users may need

**Comment by andrew-s-taylor** [comment]
Resolved in the latest version
