### ISSUE TITLE
Script may remove MSTSC

### ISSUE THREAD

**Issue by PazzoBread** [andrew-s-taylor/public#22]
mstsc is able to be uninstalled on Win11 23H2+. https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/uninstall-remote-desktop-connection. I believe this will need to be added to the whitelist. Seen this get removed on some Win11 installs. 

RegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\mstsc-4b0a31aa-df6a-4307-9b47-d5cc50009643

Guid appears to be the same across installs.  
![Screenshot 2024-01-04 164443](https://github.com/andrew-s-taylor/public/assets/75051642/26036258-3cf5-4bc7-8dee-376e2b17276b)

**Comment by andrew-s-taylor** [comment]
Added to whitelist in 4.1.2
