### ISSUE TITLE
No process is on the other end of the pipe

### ISSUE THREAD

**Issue by an0key** [andrew-s-taylor/public#23]
Hello, trying to give your intune/winget tool a try, it looks awesome. However I am getting the below error when I try any of the apps from the gridview... 

The temp folder, correctly downloads the IntuneWinAppUtil.exe file, however it may look like the downloaded setup file isn't in any of the temp folers...?

**********************
Windows PowerShell transcript start
Start time: 20240107195532
Username: luke
RunAs User: luke
Configuration Name: 
Machine: TestEUD-00000001 (Microsoft Windows NT 10.0.22631.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 10616
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\luke\AppData\Local\Temp\intune-07012024.log
Installing Intune modules if required (current user scope)
Installing Intune modules if required (current user scope)
PowerShell YAML Already Installed
Installing Microsoft Graph modules if required (current user scope)
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Microsoft Graph Already Installed
Directory already existed

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        07/01/2024     19:55                485-2401075556
winget already installed
Running PowerShell 5
Version 2 module detected
Connected to Intune tenant
VERBOSE: 7-Zip Selected with ID of 7zip.7zip
VERBOSE: Creating Directory for 7-Zip

    Directory: C:\temp\485-2401075556

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        07/01/2024     19:56                7zip.7zip
Directory c:\temp\485-2401075556\\7zip.7zip Created
VERBOSE: Creating AAD Groups for 7-Zip
Created 2ff6b059-f165-472d-9326-abc9b26442fe for installing 7-Zip
Created 0a249b46-c084-45aa-bed6-35db3792d839 for uninstalling 7-Zip
VERBOSE: Creating Install Script for 7-Zip
Script created at c:\temp\485-2401075556\\7zip.7zip\install7zip.7zip.ps1
VERBOSE: Creating Uninstall Script for 7-Zip
Script created at c:\temp\485-2401075556\\7zip.7zip\uninstall7zip.7zip.ps1
VERBOSE: Creating Detection Script for 7-Zip
Script created at c:\temp\485-2401075556\\7zip.7zip\detection7zip.7zip.ps1
VERBOSE: Creation Proactive Remediation for 7-Zip
VERBOSE: POST https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts with 1475-byte payload
VERBOSE: received 1744-byte response of content type application/json
VERBOSE: POST https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts/677ed4ba-f3ff-44a4-a73f-8dd0181081ce/assign with 958-byte payload
VERBOSE: received 0-byte response of content type
Success
Proactive Remediation Created and Assigned for 7-Zip
VERBOSE: Creating Intunewin File for 7-Zip
PS>TerminatingError(): "The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while setting the console window title. Contact Microsoft Customer Support Services."
The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while setting the console window 
title. Contact Microsoft Customer Support Services.
At C:\Code\deploy-winget-win32-multiple.ps1:2447 char:5
+     . $intuneapputiloutput -c "$apppath" -s "$setupfilename" -o "$app ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], HostException
    + FullyQualifiedErrorId : SetConsoleWindowTitle
The Win32 internal error "No process is on the other end of the pipe" 0xE9
>> TerminatingError(): "The pipeline has been stopped."
>> TerminatingError(): "The pipeline has been stopped."
>> TerminatingError(out-lineoutput): "The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services."
The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
out-lineoutput : The Win32 internal error "No process is on the other end of
>> TerminatingError(out-lineoutput): "The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services."
The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
**********************
Windows PowerShell transcript end
End time: 20240107195700
**********************

**Comment by andrew-s-taylor** [comment]
Are you running as admin?  There isn't an exe download with winget, that's all at the client side
