### ISSUE TITLE
McAfee uninstall not working completely

### ISSUE THREAD

**Issue by linczakjw** [andrew-s-taylor/public#24]
Hey there!  Appreciate the work you've done on this!  Was testing this just by running the script manually for now - we'll add to MDM shortly.  Running on Lenovo E14 running Windows 11 and was hoping it would remove the McAfee trial, but it doesn't seem to.  Before or after restart, McAfee is listed in Add/Remove Programs, but now I can't uninstall it manually that way - no apps come up as being able to remove, and the app is still running in the system tray. Any thoughts or anything I can provide to help troubleshoot.

Heads-up, not a Windows admin expert, so go easy on me.  ;) 

Jon

**Comment by andrew-s-taylor** [comment]
Hi Jon,
I think McAfee have changed their installer which has stopped this method from working.
Can you try the ESET removal tool (option 2) from here and see if that works?
https://www.urtech.ca/2019/04/sovled-mcafee-removal-tool-uninstaller/

That has silent commands so if it does, I can include that in the script

**Comment by andrew-s-taylor** [comment]
Ah, it can be a complex removal.  I could delay until it's completed, but that would slow down Autopilot (and possibly time it out) and I prefer to have the user up and running quickly and let things happen in the background.
Happy to talk you through changing it though if you want your copy to wait

**Comment by linczakjw** [comment]
Nah, it makes sense what you are saying, and for me, I'm watching the script intently for testing, whereas others would never  really care or be checking.  Appreciate the quick responses, and the script!  It helped a ton in a pinch!
