### ISSUE TITLE
Removing McAfee SafeConnect

### ISSUE THREAD

**Issue by jamie8johnson** [andrew-s-taylor/public#26]
FYI, to remove McAfee SafeConnect in Debloat, I had to run the command:

start-process "C:\ProgramData\Package Cache\{1d4027d4-d88e-4514-8e61-0ad4d485ba85}\McAfeeSafeConnect.exe" -ArgumentList "/uninstall"

**Comment by andrew-s-taylor** [comment]
Thank you, is the app ID the same across devices?

**Comment by jamie8johnson** [comment]
Yes

**Comment by andrew-s-taylor** [comment]
I've added it to 4.1.6

**Comment by jamie8johnson** [comment]
I found a some different app ID's on a few endpoints, so this needs to be done with a loop through the uninstall strings, unfortunately. The name to find is just "McAfee Safe Connect"

**Comment by andrew-s-taylor** [comment]
I've added that into the latest version
