### ISSUE TITLE
De-Bloat/RemoveBloat.ps1 customwhitelist option

### ISSUE THREAD

**Issue by thenamelessthing** [andrew-s-taylor/public#27]
Hi, it look like the customwhitelist option doesn't work.

I checked the app's name with:

![image](https://github.com/andrew-s-taylor/public/assets/10235448/80cf133c-d7ff-42d4-9fc3-41e24bc3e816)

if I run the following command:
.\removebloat.ps1 -customwhitelist "DellInc.DellCommandUpdate"

I got:

![image](https://github.com/andrew-s-taylor/public/assets/10235448/240f1b39-3483-4c43-b0e9-3a9fbf9a9551)

**Comment by andrew-s-taylor** [comment]
Can you try this:
$arguments = '-customwhitelist "DellInc.DellCommandUpdate"'
invoke-expression -Command $templateFilePath $arguments

**Comment by andrew-s-taylor** [comment]
I've just updated the script on GitHub as well, add your apps into the speechmarks in the $arguments variable

**Comment by thenamelessthing** [comment]
Hi, same problem.

![image](https://github.com/andrew-s-taylor/public/assets/10235448/ff535763-3694-4302-afd0-27b20c63760f)

**Comment by thenamelessthing** [comment]
I thought that this time it was the right one. The message indicating that the application has been found and that it is proceeding to uninstall is no longer there. However, after several minutes, the script finishes and the application is uninstalled!

![image](https://github.com/andrew-s-taylor/public/assets/10235448/af781c4b-c6c6-43c1-a4bc-3a42cfec5688)

**Comment by thenamelessthing** [comment]
Here is the apps currently installed on my PC.

![image](https://github.com/andrew-s-taylor/public/assets/10235448/1eb3dd2e-7f80-4c99-b908-c82294c25923)

If I run the command to find installed package:

![image](https://github.com/andrew-s-taylor/public/assets/10235448/c4bc475a-e2b2-40ae-b2d1-11db4800248d)

I only see one Dell application, and it's still uninstalled.

**Comment by andrew-s-taylor** [comment]
What is the uninstall command for the second one?

**Comment by thenamelessthing** [comment]
In fact, it's the same application in both results. It's just that, depending on the command, the application name is not the same. At least, that's what I think according to my checks.

**Comment by andrew-s-taylor** [comment]
They have different versions and file sizes.
The app removal method is different for installed apps and appx so it would be good to confirm which these are

**Comment by thenamelessthing** [comment]
I found no reference for the first one (Dell Command | Update) only for the the second one..

**Comment by andrew-s-taylor** [comment]
Any chance you can send the full logs it has generated?
