### ISSUE TITLE
intune-inventory-discovered-apps reduce requested privileges

### ISSUE THREAD

**Issue by philixx93** [andrew-s-taylor/public#29]
Hi,
intune-inventory-discovered-apps.ps1 requests quite a lot of privileges that it does no need. I reduced the Scopes in line 147 to "DeviceManagementApps.Read.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.Read.All" and it works just fine.

Greets, Philipp

**Comment by andrew-s-taylor** [comment]
Thank you, updated now
