### ISSUE TITLE
Security issue in (atleast) the Dell driver update script

### ISSUE THREAD

**Issue by LickABrick** [andrew-s-taylor/public#3]
Hi I stumbled upon your script/method for automated driver updates for Dell devices. I've found a potential security issue in the method used.

The method used writes a 'runupdate.bat' script to the client. A scheduled task is created which periodically runs the 'runupdate.bat' script.

The problem is the 'runupdate.bat' script is editable by users (even without Local Administrator permissions).  A user could edit the script and add things such as 'net localgroup administrators azuread\user.name@domain.com /add' which will be executed by the scheduled task (which has local admin permissions). In this case it will add the specified user to the 'Administrators' group on the client.

A possible solution would be to edit the scheduled task and instead of running the runupdate.bat script directly call the command which is specified in the runupdate.bat script. Or you could set the permissions on the runupdate.bat file within the install.bat file.

_I have not fully tested this solution for flaws but will do so in the coming days._

**Comment by andrew-s-taylor** [comment]
Well spotted, thank you.  Script and intunewin package have been updated and now call the command directly.
Due to the difference in the HP tool, it's now 2 scheduled tasks instead of just one
