### ISSUE TITLE
Add Remove Pinned Store from Taskbar and Dropbox promotion

### ISSUE THREAD

**Issue by marnold-sysadmin** [andrew-s-taylor/public#30]
Thoughts on adding to the debloat script. 

#Remove Pinned Taskbar Microsoft Store
$apps = (New-Object -Com Shell.Application).NameSpace('shell:::{4234d49b-0245-4df3-b780-3893943456e1}').Items()
$finalname = $null
 
foreach ($app in $apps) {
    $appname = $app.Name
    if ($appname -like "*store*") {
        $finalname = $app.Name
        break # Optional: Break if you only need the first match
    }
}
 
if ($null -ne $finalname) {
    $verbs = ((New-Object -Com Shell.Application).NameSpace('shell:::{4234d49b-0245-4df3-b780-3893943456e1}').Items() | Where-Object {$_.Name -eq $finalname}).Verbs()
    $unpinVerb = $verbs | Where-Object {$_.Name.replace('&','') -match 'Unpin from taskbar'}
    if ($null -ne $unpinVerb) {
        $unpinVerb.DoIt()
        $exec = $true
    } else {
        Write-Host "Unpin verb not found for $finalname."
    }
} else {
    Write-Host "No application matching '*store*' found."
}

Also there is a Dropbox Promotion that I would see useful to add. 

# Removing Dropbox Promotion using wildcard for version flexibility
$dropboxPromoPackages = Get-AppxPackage -Name "C27EB4BA.DropboxOEM*"
foreach ($pkg in $dropboxPromoPackages) {
    Remove-AppxPackage -Package $pkg.PackageFullName
    Write-Host "Removed Dropbox Promotion package: $($pkg.PackageFullName)"
}

**Comment by andrew-s-taylor** [comment]
I don't think the unpin store option will work as the system user?

**Comment by marnold-sysadmin** [comment]
Yea i think you are correct. My testing didnt work until i ran the script on a user profile not as an admin.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andrew-s-taylor** [comment]
I'll add the wildcard on dropbox though.
I add the unpin store as a user script in Intune if it helps

**Comment by andrew-s-taylor** [comment]
Dropbox added
