### ISSUE TITLE
getintuneapps issue

### ISSUE THREAD

**Issue by ddepireux-belb** [andrew-s-taylor/public#33]
Hello 
I try your script but when i select an app i didn't get the assigned group, it stays blank. 
What if there are differents groups assigned and/or members. And in cas of differents assignments ?

**Comment by andrew-s-taylor** [comment]
It should list all assigned groups, but won't drill down into the group membership.

Are you using an app reg or interactive connection?

**Comment by ddepireux-belb** [comment]
just launching in powershell with the command getintuneapp with a global admin account

**Comment by ddepireux-belb** [comment]
![image](https://github.com/andrew-s-taylor/public/assets/173997754/34bd9bfc-c262-449d-b316-726fc965cc22)

**Comment by andrew-s-taylor** [comment]
Does the unmodified script work?

**Comment by ddepireux-belb** [comment]
Just to get the list of apps and when i click on them didn't get the assigned groups

**Comment by andrew-s-taylor** [comment]
For all apps?

**Comment by ddepireux-belb** [comment]
yes

**Comment by andrew-s-taylor** [comment]
Do they have multiple assignments, or single groups?

**Comment by ddepireux-belb** [comment]
i have multiple assignments and differents intent

**Comment by ddepireux-belb** [comment]
![image](https://github.com/andrew-s-taylor/public/assets/173997754/9448c6e8-4442-4f29-93a3-f2c825ed40b9)

**Comment by andrew-s-taylor** [comment]
Is that the edited script?

**Comment by ddepireux-belb** [comment]
no the inital one

**Comment by ddepireux-belb** [comment]
problem seem to come from line 395 
 $assignedgroup = (Get-AADGroup -id $Assignment.target.GroupId).displayName that return nothing.
any idea ?

**Comment by andrew-s-taylor** [comment]
You'll need to check that the ID is being passed through correctly

**Comment by ddepireux-belb** [comment]
what does refer -id in $assignedgroup = (Get-AADGroup -id $Assignment.target.GroupId).displayName ?

**Comment by andrew-s-taylor** [comment]
It's the ID of the Entra ID group

**Comment by ddepireux-belb** [comment]
seems that function get-AADgroup doesn't work , I try to put messagebox to show where is the app but no response
