### ISSUE TITLE
Dell Bloat - removing non specified dell applications

### ISSUE THREAD

**Issue by tjeaton** [andrew-s-taylor/public#34]
The Dell bloat removal process removes more that what is actually specified it should remove.

- Dell Command | Endpoint Configure for Microsoft Intune
- Microsoft Update Health Tools

The following specified programs will cause this behaviour 

"Dell Command | Update"
"Dell Command | Update for Windows Universal"
"Dell Command | Update for Windows 10"
"Dell Command | Power Manager"

When checking with `Get-CimInstance -ClassName Win32_Product | Where-Object Name -Match "Dell Command | Update"`

It returned back the apps as mentioned
- Dell Command | Endpoint Configure for Microsoft Intune
- Dell Command | Configure
- Microsoft Update Health Tools

I belive this is happening to due to the pipe symbol in the string - I tested with attempting to escaping the pipe symbol with a backslash which sort of works but not perfect.

When checking with `Get-CimInstance -ClassName Win32_Product | Where-Object Name -Match "Dell Command \| Endpoint"`

Still showed the output Dell Command | Endpoint Configure for Microsoft Intune - so it's not able to perform a full exact match still.

**Comment by andrew-s-taylor** [comment]
Can you see what happens if you replace the "" with '':
'Dell Command | Update'

Otherwise a backtick is the escape string in PS `

**Comment by tjeaton** [comment]
Tested with single quotes - `Get-CimInstance -ClassName Win32_Product | Where-Object Name -Match 'Dell Command | Update'`
Same outcome as before

Tested with backtick on pipe `Get-CimInstance -ClassName Win32_Product | Where-Object Name -Match 'Dell Command `| Update'`
Output was just Microsoft Update Health Tools

**Comment by andrew-s-taylor** [comment]
Try this:
Get-CimInstance -ClassName Win32_Product | Where-Object Name -Match "Dell Command `| Update"

I don't have a Dell to test this unfortunately

**Comment by tjeaton** [comment]
> Try this: Get-CimInstance -ClassName Win32_Product | Where-Object Name -Match "Dell Command `| Update"
> 
> I don't have a Dell to test this unfortunately

Tested this also but output still shows the same 3 applications as mentioned originally.

**Comment by tjeaton** [comment]
Okay I may have a workaround which appears to be working

`Get-CimInstance -Query "SELECT * FROM Win32_Product WHERE name = 'Dell Command | Update'"`
This returns 0 results

However when I run
`Get-CimInstance -Query "SELECT * FROM Win32_Product WHERE name = 'Dell Command | Endpoint Configure for Microsoft Intune'"`
It only returns the installed application Dell Command | Endpoint Configure for Microsoft Intune

Tested with these and appears to be working as expected now
"Dell Command | Update"
"Dell Command | Update for Windows Universal"
"Dell Command | Update for Windows 10"
"Dell Command | Power Manager"

**Comment by andrew-s-taylor** [comment]
Does that work within the app loop as well?

**Comment by tjeaton** [comment]
> Does that work within the app loop as well?

Tested with the loop - I had to put single quotes around $program

`Get-CimInstance -Query "SELECT * FROM Win32_Product WHERE name = '$program'" | Invoke-CimMethod -MethodName Uninstall`

Works as expected now

**Comment by tjeaton** [comment]
> Does that work within the app loop as well?

Yes it appears so

Tested with the loop - I had to put single quotes around $program

`Get-CimInstance -Query "SELECT * FROM Win32_Product WHERE name = '$program'" | Invoke-CimMethod -MethodName Uninstall`

**Comment by andrew-s-taylor** [comment]
Thank you, just pushed out a new version with the fix

**Comment by tjeaton** [comment]
#

> > Does that work within the app loop as well?
> 
> Yes it appears so
> 
> Tested with the loop - I had to put single quotes around $program
> 
> `Get-CimInstance -Query "SELECT * FROM Win32_Product WHERE name = '$program'" | Invoke-CimMethod -MethodName Uninstall`

Issue Resolved.

**Comment by tjeaton** [comment]
#

> > Does that work within the app loop as well?
> 
> Yes it appears so
> 
> Tested with the loop - I had to put single quotes around $program
> 
> `Get-CimInstance -Query "SELECT * FROM Win32_Product WHERE name = '$program'" | Invoke-CimMethod -MethodName Uninstall`

Issue Resolved.
