### ISSUE TITLE
function UninstallAppFull - doesn't do anything

### ISSUE THREAD

**Issue by tjeaton** [andrew-s-taylor/public#35]
https://github.com/andrew-s-taylor/public/blob/77f854aca314d19631d3e31740d4c02ae611513c/De-Bloat/RemoveBloat.ps1#L1414C9-L1416C70

The function UninstallAppFull

Seems to create the neccessary uninstall string but towards the end of the function the uninstall string is never called as it's commented out.

```
Write-Host "Uninstalling: $displayName"
#Start-Process $string2
Write-Host "Uninstalled: $displayName" -ForegroundColor Green
```
Is this expected?

**Comment by andrew-s-taylor** [comment]
Yes, it was causing some issues
