### ISSUE TITLE
Remove bloat script Start menu widgets

### ISSUE THREAD

**Issue by Typhoon87** [andrew-s-taylor/public#36]
I was wondering if you can not what part of the debloat script would block start menu widgets. I don't see any specific notice so am not sure what module to whitelist? idea

**Comment by andrew-s-taylor** [comment]
Which widgets is it blocking?

**Comment by Typhoon87** [comment]
The entire widgets in taskbar is unavailable. We are using the debloat script in SCCM OSD Task Sequence for Win 11 23H2 and it seems to be turning off the widgets (see screenshot) it says managed by org but we are not using any Group Policy to disable this.

If we disable the debloat script and image a machine with the rest of the Task sequence untouched it works fine. Walking the script I don't see what is touching this function.

![image](https://github.com/user-attachments/assets/c4bd611a-0717-4577-aa2b-b8aa90251902)

**Comment by andrew-s-taylor** [comment]
It'll be this:
##Disable Feeds
$registryPath = "HKLM:\SOFTWARE\Policies\Microsoft\Dsh"
If (!(Test-Path $registryPath)) { 
    New-Item $registryPath
}
Set-ItemProperty $registryPath "AllowNewsAndInterests" -Value 0
write-host "Disabled Feeds"

Lines 878-884

**Comment by Typhoon87** [comment]
Okay I was looking for widget not feed in the name. So if I just comment out that block it should work and not break anything else in the script?

**Comment by andrew-s-taylor** [comment]
Yes, the rest will work fine with that section commented out

**Comment by Typhoon87** [comment]
Thanks looks like that worked
