### ISSUE TITLE
Debloat Install Issue

### ISSUE THREAD

**Issue by tsitsavvy** [andrew-s-taylor/public#37]
Hello, we are attempting to work this script into our Autopilot for a complete hands off experience for our users. However, sometimes when this script gets deployed through Intune the script will fail due to the fact that Autopilot is trying to install programs while the script is uninstalling programs. Do you know of the best way to circumvent this? Possibly a delay on letting the script to run?

Thanks!

**Comment by andrew-s-taylor** [comment]
Hi,
Are you deploying as a platform script?  If you know how long the apps take to install, you could just add a sleep to the Intune script so it thinks it is still running which will stall the next steps

**Comment by tsitsavvy** [comment]
We are deploying this as an App. I tried setting this up as a Platform script and got an error when I tried.

**Comment by andrew-s-taylor** [comment]
I find platform script usually runs better.

If running as an app, you could make the detection script look for the completed message in the log file so you know it's done before the next app starts.  You might also want to consider using dependancies to ensure it deploys first

**Comment by tsitsavvy** [comment]
Ok, I will give that a try. If I did want to go the platform script way, do I need to make sure script signature check is turned off? I forked off the repo and commented out some stuff I did not want removed.

**Comment by andrew-s-taylor** [comment]
Yes, if it has been edited the signature will no longer be valid.

It needs to be in 64-bit and running in system context as well

**Comment by tsitsavvy** [comment]
I just tried to deploy using platform script, the script will download in ProgramData but there is no log. Intune also shows Error.

**Comment by andrew-s-taylor** [comment]
Do you have anything blocking powershell on the devices?

What does the intune registry entry report back as the failure reason?

**Comment by tsitsavvy** [comment]
Apologies, where would that be located? I am looking in Intune and cannot find a failure reason. Sorry I am new to Intune so trying to get used to how it works.

**Comment by tsitsavvy** [comment]
Please excuse my last reply. I looked in the script code and I accidentally didn't invoke the raw code. It's currently running, and possibly the only issue I see was McAfee didn't uninstall. I am gonna let the device sit a little longer and see what happens.

**Comment by tsitsavvy** [comment]
The script ran, most of the items were removed. However, when getting to McAfee I get the following error in the Debloat log.

PermissionDenied: C:\ProgramData\Debloat\mccleanup.exe:FileInfo [Remove-Item], UnauthorizeAccessException
RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand

Any idea?

**Comment by andrew-s-taylor** [comment]
Sometimes McAfee needs a reboot to fully remove

**Comment by tsitsavvy** [comment]
I rebooted and checked the registry for errors. I also checked Debloat log and stops now at Detecting McAfee and goes straight to completed. I checked and seems like some McAfee residue still remains.

**Comment by andrew-s-taylor** [comment]
That error is from one of the Lenovo uninstall scripts, I see that one a lot, but there isn't anything I can do as it's an uninstall script already on the device.

Which parts of mcafee are left? It might just need some manual cleanup added

**Comment by tsitsavvy** [comment]
Gotcha, I do thank you for taking the time to help at least!
It looks like the shortcut is still in the start menu and pinned.
There are also McAfee and McAfeeDashboard under Program Files. I also found a McAfee folder under Program Files\Common Files
Would something like a Remediation script suffice to remove the rest or is there an easier way?

**Comment by andrew-s-taylor** [comment]
A remediation script would work.  If you send me a full list of files, I can try and add them to the script
