### ISSUE TITLE
Typo in the Lenovo Camera fix on RemoveBloat.ps1

### ISSUE THREAD

**Issue by alvillar** [andrew-s-taylor/public#38]
On the script RemoveBloat.ps1

The line 1827 is:
$keypath2 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows Media Foundation\Platform key"

Should be:
$keypath2 = "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows Media Foundation\Platform"

Thanks great script!

**Comment by andrew-s-taylor** [comment]
Thank you, that's sorted now :)
