### ISSUE TITLE
Logical error in UninstallAppFull function

### ISSUE THREAD

**Issue by WooconAdam** [andrew-s-taylor/public#42]
Hi,

Great work! In your script and the _UninstallAppFull_ function we have these lines:

```
if ($uninstallString -match "^msiexec*") {
            #MSI install, replace the I with an X and make it quiet
            $string2 = $uninstallString + " /quiet /norestart"
            $string2 = $uninstallString -replace "/I", "/X "
}
```

I assume it should be as below as we otherwise are not getting the " /quiet /norestart":

```
if ($uninstallString -match "^msiexec*") {
            #MSI install, replace the I with an X and make it quiet
            $string2 = $uninstallString + " /quiet /norestart"
            $string2 = $string2 -replace "/I", "/X "
 }
```

Proof:
> $uninstallString = "file.msi /I"
> $string2 = $uninstallString + " /quiet /norestart"
> $string2
Output: _file.msi /I /quiet /norestart_

> $string2 = $uninstallString -replace "/I", "/X "
> $string2
Output: _file.msi /X_

**Comment by andrew-s-taylor** [comment]
Thank you, I'd missed that.  Updated now :)

**Comment by WooconAdam** [comment]
Resolved
