### ISSUE TITLE
Issue with the last release on the locales part

### ISSUE THREAD

**Issue by alvillar** [andrew-s-taylor/public#45]
Hello, 

I'm getting an error on the script as it tries to run and the main issue is on the locale

Line 172 as it leaves the quotes open and everything else fails...

also in line 223

I try to manually remove the locales and works.. so probably that is causing the issue 

Thanks!

**Comment by andrew-s-taylor** [comment]
Is this the de-bloat script?  I can't see any open quotes on line 172

**Comment by alvillar** [comment]
![image](https://github.com/user-attachments/assets/ecbbf535-29dc-456d-891a-91212c60dbb1)

This is a screenshot, sorry I can't get more data from the computer yet...

**Comment by alvillar** [comment]
PS C:\ProgramData\Debloat> .\removebloat.ps1
En C:\ProgramData\Debloat\removebloat.ps1: 172 Carácter: 26
+         $everyone = "Ø§Ù„Ø¬Ù…ÙŠØ¹"
+                          ~~~~~~~~~
Token 'Ø¬Ù…ÙŠØ¹"
        $builtin = "Ù…Ø¯Ù…Ø¬"
    }
    "bg-BG" {
        $everyone = "Ð’ÑÐ¸Ñ‡ÐºÐ¸"
        $builtin = "Ð’Ð³Ñ€Ð°Ð´ÐµÐ½"
    }
    "cs-CZ" {
        $everyone = "VÅ¡ichni"
        $builtin = "VestavÄ›nÃ½"
    }
    "da-DK" {
        $everyone = "Alle"
        $builtin = "Indbygget"
    }
    "de-DE" {
        $everyone = "Jeder"
        $builtin = "Integriert"
    }
    "el-GR" {
        $everyone = "ÎŒÎ»Î¿Î¹"
        $builtin = "Î•Î½ÏƒÏ‰Î¼Î±Ï„Ï‰Î¼Î­Î½Î¿"' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 223 Carácter: 6
+     "hr-HR" {
+      ~~~~~~~~
Token 'hr-HR" {
        $everyone = "Svi"
        $builtin = "UgraÄ‘eni"
    }
    "hu-HU" {
        $everyone = "Mindenki"
        $builtin = "BeÃ©pÃ­tett"
    }
    "it-IT" {
        $everyone = "Tutti"
        $builtin = "Incorporato"
    }
    "ja-JP" {
        $everyone = "ã™ã¹ã¦ã®ãƒ¦ãƒ¼ã‚¶ãƒ¼"
        $builtin = "ãƒ“ãƒ«ãƒˆã‚¤ãƒ³"' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 240 Carácter: 29
+         $everyone = "ëª¨ë“  ì‚¬ìš©ìž"
+                             ~~~~~~~~~~
Token 'ì‚¬ìš©ìž"
        $builtin = "ê¸°ë³¸ ì œê³µ"
    }
    "lt-LT" {
        $everyone = "Visi"
        $builtin = "Ä®montuotas"
    }
    "lv-LV" {
        $everyone = "Visi"
        $builtin = "IebÅ«vÄ“ts"
    }
    "nb-NO" {
        $everyone = "Alle"
        $builtin = "Innebygd"
    }
    "nl-NL" {
        $everyone = "Iedereen"
        $builtin = "Ingebouwd"
    }
    "pl-PL" {
        $everyone = "Wszyscy"
        $builtin = "Wbudowany"
    }
    "pt-BR" {
        $everyone = "Todos"
        $builtin = "Integrado"
    }
    "pt-PT" {
        $everyone = "Todos"
        $builtin = "Incorporado"
    }
    "ro-RO" {
        $everyone = "ToatÄƒ lumea"
        $builtin = "Incorporat"
    }
    "ru-RU" {
        $everyone = "Ð’ÑÐµ' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 297 Carácter: 42
+         $builtin = "à¸ à¸²à¸¢à¹ƒà¸™à¹€à¸„à¸£à¸·à¹ˆà¸­à¸‡"
+                                          ~~~~~~~~~~~~~~~~
Token 'à¸£à¸·à¹ˆà¸­à¸‡"
    }
    "tr-TR" {
        $everyone = "Herkes"
        $builtin = "YerleÅŸik"
    }
    "uk-UA" {
        $everyone = "Ð’ÑÑ–"
        $builtin = "Ð’Ð±ÑƒÐ´Ð¾Ð²Ð°Ð½Ð¸Ð¹"
    }
    "zh-CN" {
        $everyone = "æ‰€æœ‰äºº"
        $builtin = "å†…ç½®"
    }
    "zh-TW" {
        $everyone = "æ‰€æœ‰äºº"
        $builtin = "å…§å»º"
    }
    default {
        $everyone = "Everyone"
        $builtin = "Builtin"
    }
}
############################################################################################################
#                                        Remove AppX Packages                                              #
#                                                                                                          #
############################################################################################################
#Removes AppxPackages
$WhitelistedApps = @(
    'Microsoft.WindowsNotepad',
    'Microsoft.CompanyPortal',
    'Microsoft.ScreenSketch',
    'Microsoft.Paint3D',
    'Microsoft.WindowsCalculator',
    'Microsoft.WindowsStore',
    'Microsoft.Windows.Photos',
    'CanonicalGroupLimited.UbuntuonWindows',
    'Microsoft.MicrosoftStickyNotes',
    'Microsoft.MSPaint',
    'Microsoft.WindowsCamera',
    '.NET Framework',
    'Microsoft.HEIFImageExtension',
    'Microsoft.ScreenSketch',
    'Microsoft.StorePurchaseApp',
    'Microsoft.VP9VideoExtensions',
    'Microsoft.WebMediaExtensions',
    'Microsoft.WebpImageExtension',
    'Microsoft.DesktopAppInstaller',
    'WindSynthBerry',
    'MIDIBerry',
    'Slack',
    'Microsoft.SecHealthUI',
    'WavesAudio.MaxxAudioProforDell2019',
    'Dell Optimizer Core',
    'Dell SupportAssist Remediation',
    'Dell SupportAssist OS Recovery Plugin for Dell Update',
    'Dell Pair',
    'Dell Display Manager 2.0',
    'Dell Display Manager 2.1',
    'Dell Display Manager 2.2',
    'Dell Peripheral Manager',
    'MSTeams',
    'Microsoft.Paint',
    'Microsoft.OutlookForWindows',
    'Microsoft.WindowsTerminal',
    'Microsoft.MicrosoftEdge.Stable'
)
##If $customwhitelist is set, split on the comma and add to whitelist
if ($customwhitelist) {
    $customWhitelistApps = $customwhitelist -split "' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 368 Carácter: 53
+     $customWhitelistApps = $customwhitelist -split ","
+                                                     ~
Falta un argumento en la lista de parámetros.
En C:\ProgramData\Debloat\removebloat.ps1: 1176 Carácter: 20
+     Write-Output " <LayoutOptions StartTileGroupCellWidth=""6"" />" > ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1178 Carácter: 20
+     Write-Output " <DefaultLayoutOverride>" >> C:\Windows\StartLayout ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1180 Carácter: 20
+     Write-Output " <StartLayoutCollection>" >> C:\Windows\StartLayout ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1182 Carácter: 20
+     Write-Output " <defaultlayout:StartLayout GroupCellWidth=""6"" /> ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1184 Carácter: 20
+     Write-Output " </StartLayoutCollection>" >> C:\Windows\StartLayou ...
+                    ~
El operador '<' está reservado para uso futuro.
No se notificaron todos los errores de análisis. Corrija los errores notificados e inténtelo de nuevo.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by alvillar** [comment]
`PS C:\ProgramData\Debloat> .\removebloat.ps1
En C:\ProgramData\Debloat\removebloat.ps1: 172 Carácter: 26
+         $everyone = "Ø§Ù„Ø¬Ù…ÙŠØ¹"
+                          ~~~~~~~~~
Token 'Ø¬Ù…ÙŠØ¹"
        $builtin = "Ù…Ø¯Ù…Ø¬"
    }
    "bg-BG" {
        $everyone = "Ð’ÑÐ¸Ñ‡ÐºÐ¸"
        $builtin = "Ð’Ð³Ñ€Ð°Ð´ÐµÐ½"
    }
    "cs-CZ" {
        $everyone = "VÅ¡ichni"
        $builtin = "VestavÄ›nÃ½"
    }
    "da-DK" {
        $everyone = "Alle"
        $builtin = "Indbygget"
    }
    "de-DE" {
        $everyone = "Jeder"
        $builtin = "Integriert"
    }
    "el-GR" {
        $everyone = "ÎŒÎ»Î¿Î¹"
        $builtin = "Î•Î½ÏƒÏ‰Î¼Î±Ï„Ï‰Î¼Î­Î½Î¿"' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 223 Carácter: 6
+     "hr-HR" {
+      ~~~~~~~~
Token 'hr-HR" {
        $everyone = "Svi"
        $builtin = "UgraÄ‘eni"
    }
    "hu-HU" {
        $everyone = "Mindenki"
        $builtin = "BeÃ©pÃ­tett"
    }
    "it-IT" {
        $everyone = "Tutti"
        $builtin = "Incorporato"
    }
    "ja-JP" {
        $everyone = "ã™ã¹ã¦ã®ãƒ¦ãƒ¼ã‚¶ãƒ¼"
        $builtin = "ãƒ“ãƒ«ãƒˆã‚¤ãƒ³"' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 240 Carácter: 29
+         $everyone = "ëª¨ë“  ì‚¬ìš©ìž"
+                             ~~~~~~~~~~
Token 'ì‚¬ìš©ìž"
        $builtin = "ê¸°ë³¸ ì œê³µ"
    }
    "lt-LT" {
        $everyone = "Visi"
        $builtin = "Ä®montuotas"
    }
    "lv-LV" {
        $everyone = "Visi"
        $builtin = "IebÅ«vÄ“ts"
    }
    "nb-NO" {
        $everyone = "Alle"
        $builtin = "Innebygd"
    }
    "nl-NL" {
        $everyone = "Iedereen"
        $builtin = "Ingebouwd"
    }
    "pl-PL" {
        $everyone = "Wszyscy"
        $builtin = "Wbudowany"
    }
    "pt-BR" {
        $everyone = "Todos"
        $builtin = "Integrado"
    }
    "pt-PT" {
        $everyone = "Todos"
        $builtin = "Incorporado"
    }
    "ro-RO" {
        $everyone = "ToatÄƒ lumea"
        $builtin = "Incorporat"
    }
    "ru-RU" {
        $everyone = "Ð’ÑÐµ' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 297 Carácter: 42
+         $builtin = "à¸ à¸²à¸¢à¹ƒà¸™à¹€à¸„à¸£à¸·à¹ˆà¸­à¸‡"
+                                          ~~~~~~~~~~~~~~~~
Token 'à¸£à¸·à¹ˆà¸­à¸‡"
    }
    "tr-TR" {
        $everyone = "Herkes"
        $builtin = "YerleÅŸik"
    }
    "uk-UA" {
        $everyone = "Ð’ÑÑ–"
        $builtin = "Ð’Ð±ÑƒÐ´Ð¾Ð²Ð°Ð½Ð¸Ð¹"
    }
    "zh-CN" {
        $everyone = "æ‰€æœ‰äºº"
        $builtin = "å†…ç½®"
    }
    "zh-TW" {
        $everyone = "æ‰€æœ‰äºº"
        $builtin = "å…§å»º"
    }
    default {
        $everyone = "Everyone"
        $builtin = "Builtin"
    }
}
############################################################################################################
#                                        Remove AppX Packages                                              #
#                                                                                                          #
############################################################################################################
#Removes AppxPackages
$WhitelistedApps = @(
    'Microsoft.WindowsNotepad',
    'Microsoft.CompanyPortal',
    'Microsoft.ScreenSketch',
    'Microsoft.Paint3D',
    'Microsoft.WindowsCalculator',
    'Microsoft.WindowsStore',
    'Microsoft.Windows.Photos',
    'CanonicalGroupLimited.UbuntuonWindows',
    'Microsoft.MicrosoftStickyNotes',
    'Microsoft.MSPaint',
    'Microsoft.WindowsCamera',
    '.NET Framework',
    'Microsoft.HEIFImageExtension',
    'Microsoft.ScreenSketch',
    'Microsoft.StorePurchaseApp',
    'Microsoft.VP9VideoExtensions',
    'Microsoft.WebMediaExtensions',
    'Microsoft.WebpImageExtension',
    'Microsoft.DesktopAppInstaller',
    'WindSynthBerry',
    'MIDIBerry',
    'Slack',
    'Microsoft.SecHealthUI',
    'WavesAudio.MaxxAudioProforDell2019',
    'Dell Optimizer Core',
    'Dell SupportAssist Remediation',
    'Dell SupportAssist OS Recovery Plugin for Dell Update',
    'Dell Pair',
    'Dell Display Manager 2.0',
    'Dell Display Manager 2.1',
    'Dell Display Manager 2.2',
    'Dell Peripheral Manager',
    'MSTeams',
    'Microsoft.Paint',
    'Microsoft.OutlookForWindows',
    'Microsoft.WindowsTerminal',
    'Microsoft.MicrosoftEdge.Stable'
)
##If $customwhitelist is set, split on the comma and add to whitelist
if ($customwhitelist) {
    $customWhitelistApps = $customwhitelist -split "' inesperado en la expresión o la instrucción.
En C:\ProgramData\Debloat\removebloat.ps1: 368 Carácter: 53
+     $customWhitelistApps = $customwhitelist -split ","
+                                                     ~
Falta un argumento en la lista de parámetros.
En C:\ProgramData\Debloat\removebloat.ps1: 1176 Carácter: 20
+     Write-Output " <LayoutOptions StartTileGroupCellWidth=""6"" />" > ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1178 Carácter: 20
+     Write-Output " <DefaultLayoutOverride>" >> C:\Windows\StartLayout ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1180 Carácter: 20
+     Write-Output " <StartLayoutCollection>" >> C:\Windows\StartLayout ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1182 Carácter: 20
+     Write-Output " <defaultlayout:StartLayout GroupCellWidth=""6"" /> ...
+                    ~
El operador '<' está reservado para uso futuro.
En C:\ProgramData\Debloat\removebloat.ps1: 1184 Carácter: 20
+     Write-Output " </StartLayoutCollection>" >> C:\Windows\StartLayou ...
+                    ~
El operador '<' está reservado para uso futuro.
No se notificaron todos los errores de análisis. Corrija los errores notificados e inténtelo de nuevo.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken`

**Comment by andrew-s-taylor** [comment]
Did you download the raw file, or just copy and paste from the browser?

**Comment by alvillar** [comment]
it was downloaded using the script to deploy it using intune...

**Comment by andrew-s-taylor** [comment]
Something has gone very wrong with the encoding there.  Can you try deleting the file and re-downloading and see if they display properly.
If it still fails, let me know your Windows versions and language settings and I'll do some testing

**Comment by andrew-s-taylor** [comment]
I've just pushed a new version, can you try that please?

**Comment by alvillar** [comment]
[removebloat.zip](https://github.com/user-attachments/files/17133824/removebloat.zip)

Same result... This is the script that was previously downloaded... 

Windows 11 Pro
Version: 10.0.22621 Compilation 22621
regional setting: es-mx

**Comment by andrew-s-taylor** [comment]
That's still 5.0.27, make sure it downloads 5.0.28

**Comment by alvillar** [comment]
It seems that works! 

Probably when I first try it, it wasn't updated yet by github...

I'm checking that the process works automatically.. I'll let you know after the tests...

**Comment by andrew-s-taylor** [comment]
Excellent, fingers crossed!
