### ISSUE TITLE
O365 removal does not work due

### ISSUE THREAD

**Issue by dmaassen** [andrew-s-taylor/public#46]
Hello,

I am trying to remove an OEM version of O365 with your debloat script. However, it does not work.

I think it is due to the following.

This line of code is run on the wrong file.

```
Start-Process -FilePath "C:\ProgramData\Debloat\odt.exe" -ArgumentList "/configure C:\ProgramData\Debloat\o365.xml" -Wait
```

The file odt.exe provided by your repo and downloaded by the script is the ODT tool itself; not a valid usage.

When this line of the de-bloat script is run, odt.exe generates an "incorrect usage" dialog.

My hunch is that what you actually wanted to do is run the above line on `setup.exe`, which is found after running `odt /extract`. But the wrong file was provided.

cheers and thanks for your work.

**Comment by andrew-s-taylor** [comment]
Thank you, sometimes it's the obvious things I miss!

All updated now to download and use setup.exe instead :)

**Comment by dmaassen** [comment]
Thanks for the speedy update!

Works well, cheers.

**Comment by dmaassen** [comment]
Thanks for the speedy update!

Works well, cheers.
