### ISSUE TITLE
Error in RemoveBloat.ps1 ?

### ISSUE THREAD

**Issue by D0wn3r** [andrew-s-taylor/public#5]
Hi !
I have found your amazing script and after running it, it seems to don't detect my Dell computer.
I read the code and found this

`if ($manufacturer -ccontains "Dell")`

And this doesn't work. I'm a very beginner with Powershell so after some research and test it seems you should replace "ccontains" by "match" for example.

**Comment by andrew-s-taylor** [comment]
I've pushed out an update today to fix some issues with Dell devices
