### ISSUE TITLE
De-Bloat Script Causes HP Support Assistant Popup

### ISSUE THREAD

**Issue by MNTech68** [andrew-s-taylor/public#50]
When running the De-Bloat script during startup, the logged on user is getting the prompt shown in this screen shot. 
This is on an HP Envy Windows 11 Pro Machine. 

![Capture](https://github.com/user-attachments/assets/6f898002-10a2-43dc-9bad-7cac625413e4)

**Comment by andrew-s-taylor** [comment]
Can you check the uninstall string for it in the registry please. It might need a silent parameter added in the script

**Comment by MNTech68** [comment]
We ended up imaging all the machines due to the consistent issues with removing some of the HP & McAfee bloat.  Unfortunately I don't have one with factory image anymore that I could test.
