### ISSUE TITLE
“Unverified” publisher

### ISSUE THREAD

**Issue by mravikant** [andrew-s-taylor/public#6]
Hi Andrew,

I was trying to run your powershell scripts (intune-inventory-discovered-apps.ps1 & Get-intune-apps.ps1), it is prompting for Admin consent stating “Unverified” publisher. its stating “Only accespt if you trust he publisher”, can you please give me overview of requested permissions to run above scripts?

Regards,
Ravikant

**Comment by andrew-s-taylor** [comment]
Hi Ravikant,
That's because the scripts are unsigned (code-signing certs are expensive)
If you log at the Connect-MGGraph sections of the scripts, you can see the permissions and you will get a Microsoft prompt listing them with the option to accept.

Thanks

Andrew

**Comment by mravikant** [comment]
Thank you Andrew for the clarification.
