### ISSUE TITLE
WizLink.exe apps

### ISSUE THREAD

**Issue by AIGARSJ** [andrew-s-taylor/public#8]
WizLink.exe apps not getting deleted. In my case Adobe, Amazon, Booking and LastPass.
![WizLink](https://user-images.githubusercontent.com/15418150/210316651-c86b8f7b-8927-4c81-abbe-585d47b52476.png)

**Comment by andrew-s-taylor** [comment]
Which OS version are you running?  I can't see that folder on Win11 Pro 22H2

If it's Home,  I'll spin a new test machine and add some logic into the script

**Comment by AIGARSJ** [comment]
It is Windows 11 Pro 22H2.
HP Laptop device.

**Comment by andrew-s-taylor** [comment]
Ah, it's HP only bloat.  Are there any stubs in the uninstall reg keys for it, or just those files?  If it's just the files, I'll force delete them

**Comment by AIGARSJ** [comment]
I didn't see any reg keys for it. It looks like they are located only in Start Menu and Program Files folder.

**Comment by andrew-s-taylor** [comment]
Thank you, looks like it's the brute force approach.
Any chance you can send the paths for the start menu shortcuts?
Sadly HP is the only manufacturer device I don't have for testing on
