### ISSUE TITLE
function Get-DeviceConfigurationPolicySC

### ISSUE THREAD

**Issue by randomsunrize** [andrew-s-taylor/public#9]
Hey Andrew thanks for your copy intune policy script, I've had to copy out policies within the same tenant for multiple schools. I've been using an export/import and it was more a manual process before, but this has been great using your script to copy.

so far the policies ive been copying have been good except the settings catalog which have needed extra paging. I've got by this below. Idea was from Martin Heusser [https://medium.com/@mozzeph/how-to-handle-microsoft-graph-paging-in-powershell-354663d4b32a](url)

`Function Get-DeviceConfigurationPolicySC(){
    
    <#
    .SYNOPSIS
    This function is used to get device configuration policies from the Graph API REST interface - SETTINGS CATALOG
    .DESCRIPTION
    The function connects to the Graph API Interface and gets any device configuration policies
    .EXAMPLE
    Get-DeviceConfigurationPolicySC
    Returns any device configuration policies configured in Intune
    .NOTES
    NAME: Get-DeviceConfigurationPolicySC
    #>
    
    [cmdletbinding()]
    
    param
    (
        $id
    )
    
    $graphApiVersion = "beta"
    $DCP_resource = "deviceManagement/configurationPolicies"
    
        try {
    
            if($id){
    
            $uri = "https://graph.microsoft.com/$graphApiVersion/$($DCP_resource)?`$filter=id eq '$id'"
            (Invoke-MgGraphRequest -Uri $uri -Method Get -OutputType PSObject).value
    
            }
    
            else {
    
            $uri = "https://graph.microsoft.com/$graphApiVersion/$($DCP_resource)"
            $allconfigurationsettingscatalogpages = @()
            $configurationsettingscatalog = Invoke-MgGraphRequest -Uri $uri -Method Get
            $allconfigurationsettingscatalogpages += $configurationsettingscatalog.value
            do {
                $configurationsettingscatalog = (Invoke-MgGraphRequest -Uri $configurationsettingscatalog.'@odata.nextLink' -Method Get)
                $allconfigurationsettingscatalogpages += $configurationsettingscatalog.value
            } until (
                !$configurationsettingscatalog.'@odata.nextLink'
            )

            $configurationsettingscatalog = $allconfigurationsettingscatalogpages
            $configurationsettingscatalog
    
            }
    
        }
    
        catch {
    
        $ex = $_.Exception
        $errorResponse = $ex.Response.GetResponseStream()
        $reader = New-Object System.IO.StreamReader($errorResponse)
        $reader.BaseStream.Position = 0
        $reader.DiscardBufferedData()
        $responseBody = $reader.ReadToEnd();
        Write-Host "Response content:`n$responseBody" -f Red
        Write-Error "Request to $Uri failed with HTTP Status $($ex.Response.StatusCode) $($ex.Response.StatusDescription)"
        write-host
        
    
        }
    
}`

**Comment by andrew-s-taylor** [comment]
Thank you, pagination can be a pain!  I've just added your extra content in now and pushed a new version.
I've also created a new function to do a basic version check and alert for any updates.
Glad you're finding it useful!

**Comment by randomsunrize** [comment]
All good, I've been caught out a few times now when using the newer mggraph cmdlets where I didn't specify -All in my large environment.

**Comment by randomsunrize** [comment]
Just realised there's an issue, for the function I had to add the same to the if ($Id) statement

`Function Get-DeviceConfigurationPolicySC(){
    
    <#
    .SYNOPSIS
    This function is used to get device configuration policies from the Graph API REST interface - SETTINGS CATALOG
    .DESCRIPTION
    The function connects to the Graph API Interface and gets any device configuration policies
    .EXAMPLE
    Get-DeviceConfigurationPolicySC
    Returns any device configuration policies configured in Intune
    .NOTES
    NAME: Get-DeviceConfigurationPolicySC
    #>
    
    [cmdletbinding()]
    
    param
    (
        $id
    )
    
    $graphApiVersion = "beta"
    $DCP_resource = "deviceManagement/configurationPolicies"
    
        try {
    
            if($id){
    
            $uri = "https://graph.microsoft.com/$graphApiVersion/$($DCP_resource)?`$filter=id eq '$id'"
            $allconfigurationsettingscatalogpages = @()
            $configurationsettingscatalog = Invoke-MgGraphRequest -Uri $uri -Method Get
            $allconfigurationsettingscatalogpages += $configurationsettingscatalog.value
            do {
                $configurationsettingscatalog = (Invoke-MgGraphRequest -Uri $configurationsettingscatalog.'@odata.nextLink' -Method Get)
                $allconfigurationsettingscatalogpages += $configurationsettingscatalog.value
            } until (
                !$configurationsettingscatalog.'@odata.nextLink'
            )

            $configurationsettingscatalog = $allconfigurationsettingscatalogpages
            $configurationsettingscatalog
    
            }
    
            else {
    
            $uri = "https://graph.microsoft.com/$graphApiVersion/$($DCP_resource)"
            $allconfigurationsettingscatalogpages = @()
            $configurationsettingscatalog = Invoke-MgGraphRequest -Uri $uri -Method Get
            $allconfigurationsettingscatalogpages += $configurationsettingscatalog.value
            do {
                $configurationsettingscatalog = (Invoke-MgGraphRequest -Uri $configurationsettingscatalog.'@odata.nextLink' -Method Get)
                $allconfigurationsettingscatalogpages += $configurationsettingscatalog.value
            } until (
                !$configurationsettingscatalog.'@odata.nextLink'
            )

            $configurationsettingscatalog = $allconfigurationsettingscatalogpages
            $configurationsettingscatalog
    
            }
    
        }
    
        catch {
    
        $ex = $_.Exception
        $errorResponse = $ex.Response.GetResponseStream()
        $reader = New-Object System.IO.StreamReader($errorResponse)
        $reader.BaseStream.Position = 0
        $reader.DiscardBufferedData()
        $responseBody = $reader.ReadToEnd();
        Write-Host "Response content:`n$responseBody" -f Red
        Write-Error "Request to $Uri failed with HTTP Status $($ex.Response.StatusCode) $($ex.Response.StatusDescription)"
        write-host
        
    
        }
    
}`

However I'm stuck on the adding policy part.
would it be possible to use invoke-mggraphrequest rather than invoke-msgraphrequest? save having to make a connection to msgraph on top of mggraph 

`$uri = "https://graph.microsoft.com/$graphApiVersion/$Resource"
        $policy = Get-DeviceConfigurationPolicysc -id $id
        $policy | Add-Member -MemberType NoteProperty -Name 'settings' -Value @() -Force
        #$settings = Invoke-MSGraphRequest -HttpMethod GET -Url "https://graph.microsoft.com/beta/deviceManagement/configurationPolicies/$id/settings" | Get-MSGraphAllPages
        $settings = Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/beta/deviceManagement/configurationPolicies/$id/settings" -Method GET

        if ($settings -isnot [System.Array]) {
            $policy.Settings = @($settings)
        } else {
            $policy.Settings = $settings
        }`

**Comment by randomsunrize** [comment]
oops realised you were using mggraphrequest, i'm kind of mixing ur older copy policy and the new crosstenant one. 


`try {
       # Add the policy
       $body = ([System.Text.Encoding]::UTF8.GetBytes($policy.tostring()))
    Invoke-MgGraphRequest -Uri $uri -Method Post -Body $body  -ContentType "application/json; charset=utf-8"  
    #invoke-MSGraphRequest -Url $uri -HttpMethod POST -Content $body
    }
    catch {
        Write-Error $_.Exception 
        
    }`


I tweaked this part with a settings catalog policy that has no paging to get that workin first:
"deviceManagement/configurationPolicies" {
        $graphApiVersion = 'beta'
        
        
        $uri = "https://graph.microsoft.com/$graphApiVersion/$Resource"
        $policy = Get-DeviceConfigurationPolicysc -id $id
        $policy | Add-Member -MemberType NoteProperty -Name 'settings' -Value @() -Force
        #$settings = Invoke-MSGraphRequest -HttpMethod GET -Url "https://graph.microsoft.com/beta/deviceManagement/configurationPolicies/$id/settings" | Get-MSGraphAllPages
        $settings = Invoke-MgGraphRequest -Method GET -Uri "https://graph.microsoft.com/beta/deviceManagement/configurationPolicies/$id/settings"  -OutputType PSObject
        #$settings = $settings.value
        $settingsgather = $settings.value
        #$policynextlink = $settings."@odata.nextlink"


        <#
        while ($null -ne $policynextlink)
        {
            $nextsettings = (Invoke-MgGraphRequest -Uri $policynextlink -Method Get -OutputType PSObject).value
            $policynextlink = $nextsettings."@odata.nextLink"
            $settingsgather += $nextsettings
        }
        #>

        if ($settings.'@odata.nextlink')
        {
            
        }


        $settingsfinal =  $settingsgather | select-object * -ExcludeProperty '@odata.count'
        if ($settingsfinal -isnot [System.Array]) {
            $policy.Settings = @($settingsfinal)
        } else {
            $policy.Settings = $settingsfinal
        }




but still not luck

Invoke-MgGraphRequest: POST https://graph.microsoft.com/beta/deviceManagement/configurationPolicies
HTTP/1.1 400 Bad Request


{"error":{"code":"","message":"The request is invalid.","innerError":{"message":"dCV2Policy.Settings : The Settings field is required.\r\n","date":"2023-01-23T00:17:54","request-id":"8b81ae8d-5cbf-4ef9-8a9a-fa1a60e5c92f","client-request-id":"8b81ae8d-5cbf-4ef9-8a9a-fa1a60e5c92f"}}}


Somehow settings field has gone missing?

**Comment by andrew-s-taylor** [comment]
The latest crosstenant script should already support pagination on Settings Catalog policies.
Can you share the json of one of your larger policies so I can do some further testing?

**Comment by andrew-s-taylor** [comment]
After a lot of trial and error, I now have a working script for dealing with pagination!
